#!/usr/bin/env bash
# claude-overlay/inventory.sh
# Generate INVENTORY.md — a single, always-current map of everything this overlay owns:
# absorbed skills, their upstream source + pin, drift-tracking, and which OMC agents route
# to them. Derived entirely from sources/*/provenance.json + patches/* (the single sources of
# truth), so it never goes stale the way a hand-written list would.
#
# Usage:
#   ./inventory.sh            # write INVENTORY.md (and print it)
#   ./inventory.sh --stdout   # print only, write nothing
#
# For LIVE upstream drift status, run ./reabsorb.sh (this script shows the RECORDED pin only,
# to stay fast and offline).
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WRITE=1
[ "${1:-}" = "--stdout" ] && WRITE=0

OUT="$(python3 - "$SCRIPT_DIR" <<'PY'
import glob, json, os, sys, re
root = sys.argv[1]
P = os.path.join(root, "patches")
S = os.path.join(root, "sources")

def load(p):
    try:
        with open(p) as f: return json.load(f)
    except Exception: return None

# --- owned skill bundles: patches/<pname>/skill/<sname>/ ---
bundles = {}  # sname -> pname
for sdir in glob.glob(os.path.join(P, "*", "skill", "*", "")):
    sname = os.path.basename(sdir.rstrip("/"))
    pname = os.path.basename(os.path.dirname(os.path.dirname(sdir.rstrip("/"))))
    bundles[sname] = pname

# --- provenance sources ---
sources = {}  # id -> prov
for pj in glob.glob(os.path.join(S, "*", "provenance.json")):
    prov = load(pj)
    if prov: sources[prov.get("id", os.path.basename(os.path.dirname(pj)))] = prov

def provenance_for(sname, pname):
    """Match a bundle to its source by id==name, else by any source whose
    dependents[].asset points at this bundle's patch dir (e.g. design-discovery<-insane-design)."""
    if sname in sources:
        return sources[sname]
    needle = "patches/%s/" % pname
    for prov in sources.values():
        for dep in prov.get("dependents", []):
            if needle in (dep.get("asset") or ""):
                return prov
    return None

# --- file/agent patches: patches/<pname>/target ---
patches = []  # (pname, target, marker)
for tf in glob.glob(os.path.join(P, "*", "target")):
    pname = os.path.basename(os.path.dirname(tf))
    target = open(tf).read().strip()
    mf = os.path.join(os.path.dirname(tf), "marker")
    marker = open(mf).read().strip() if os.path.exists(mf) else "-"
    patches.append((pname, target, marker))

# --- owned rules & hooks: patches/<pname>/rules|hooks/<file> (asset-only, no target/marker) ---
assets = []  # (kind, fname, pname, dest)
for kind, sub, dest in (("rule", "rules", "~/.claude/rules"), ("hook", "hooks", "~/.claude/hooks")):
    for af in glob.glob(os.path.join(P, "*", sub, "*")):
        if not os.path.isfile(af): continue
        pname = os.path.basename(os.path.dirname(os.path.dirname(af)))
        assets.append((kind, os.path.basename(af), pname, dest))

# --- routing map: which patched.md blocks mention each owned skill name ---
def routers_for(skill):
    hits = []
    for pf in glob.glob(os.path.join(P, "*", "patched.md")):
        try:
            if skill in open(pf, encoding="utf-8", errors="ignore").read():
                hits.append(os.path.basename(os.path.dirname(pf)))
        except Exception: pass
    return hits

def short(v):
    v = str(v or "-")
    v = v.replace("blob:", "")
    return v[:12] if re.fullmatch(r"[0-9a-f]{7,40}", v) else v

lines = []
lines.append("# Overlay inventory")
lines.append("")
lines.append("> Auto-generated by `./inventory.sh` from `sources/*/provenance.json` + `patches/*`.")
lines.append("> Do NOT hand-edit. Run `./reabsorb.sh` for live upstream drift; `./apply.sh` to (re)deploy.")
lines.append("")

# Section A: absorbed skills (owned bundles, joined to provenance)
lines.append("## Absorbed skills (lazy, owned)")
lines.append("")
lines.append("| skill | upstream | pinned | drift-probe | routed by |")
lines.append("|---|---|---|---|---|")
for sname in sorted(bundles):
    prov = provenance_for(sname, bundles[sname])
    if prov:
        loc = prov.get("locator", {})
        av = prov.get("absorbed_version", {})
        repo = loc.get("repo") or loc.get("plugin_key") or "-"
        repo_disp = repo.replace("https://github.com/", "") if repo else "-"
        pin = short(av.get("commit") or av.get("blob") or av.get("plugin_version"))
        dp = prov.get("drift_probe", {})
        probe = os.path.basename(dp.get("path", "")) or dp.get("kind", "-")
    else:
        repo_disp = "local (our own)"; pin = "—"; probe = "—"
    routers = [r for r in routers_for(sname)]
    routed = ", ".join(sorted(set(routers))) if routers else "— (description-trigger only)"
    lines.append("| `%s` | %s | `%s` | %s | %s |" % (sname, repo_disp, pin, probe, routed))
lines.append("")

# Section B: OMC file/agent patches (3-way merged)
lines.append("## OMC file patches (3-way merged into plugin files)")
lines.append("")
lines.append("| patch | target | marker |")
lines.append("|---|---|---|")
for pname, target, marker in sorted(patches):
    lines.append("| `%s` | `%s` | `%s` |" % (pname, target, marker))
lines.append("")

# Section C: sources without a bundle (concept/rule/hook absorptions)
orphan = [i for i in sorted(sources) if i not in bundles]
if orphan:
    lines.append("## Other absorbed sources (rules / hooks / concepts — no skill bundle)")
    lines.append("")
    lines.append("| source | type | upstream | pinned |")
    lines.append("|---|---|---|---|")
    for i in orphan:
        prov = sources[i]
        loc = prov.get("locator", {}); av = prov.get("absorbed_version", {})
        repo = (loc.get("repo") or loc.get("plugin_key") or "-")
        repo = repo.replace("https://github.com/", "")
        pin = short(av.get("commit") or av.get("blob") or av.get("plugin_version") or av.get("concept_ref"))
        lines.append("| `%s` | %s | %s | `%s` |" % (i, prov.get("source_type", "-"), repo, pin))
    lines.append("")

# Section D: owned rules & hooks (asset-only bundles, invisible to the patch/source tables)
if assets:
    lines.append("## Owned rules & hooks (mirrored verbatim, survive OMC updates)")
    lines.append("")
    lines.append("| kind | file | from bundle | deployed to |")
    lines.append("|---|---|---|---|")
    for kind, fname, pname, dest in sorted(assets):
        lines.append("| %s | `%s` | `%s` | `%s` |" % (kind, fname, pname, dest))
    lines.append("")

lines.append("---")
lines.append("_%d absorbed skill(s), %d file patch(es), %d owned rule/hook(s), %d provenance source(s)._" %
             (len(bundles), len(patches), len(assets), len(sources)))
print("\n".join(lines))
PY
)"

if [ $WRITE -eq 1 ]; then
  printf '%s\n' "$OUT" > "$SCRIPT_DIR/INVENTORY.md"
  echo "wrote $SCRIPT_DIR/INVENTORY.md"
  echo
fi
printf '%s\n' "$OUT"
